function selectAptAnalyticsURL(){let currentHost=window.location.hostname;let found2=currentHost.search('analyticsvidhya.com');if(found2!==-1){return analyticsProdURL;}else if(currentHost==='localhost'||currentHost==='localhost:8000'){return analyticsLocalURL;}else{return analyticsDevURL;}}
function getElementDetails(event){click_event_value=""
if(event.target.value!=null){click_event_value=event.target.value.trim()}
else if(event.target.lastChild!=null){click_event_value=event.target.lastChild.nodeValue}
if(click_event_value!=null){click_event_value=click_event_value.replace(/\n/g," ").trim()}
let details={id:event.target.id,class:event.target.className,value:click_event_value};return details;}
if(typeof userEmail==='undefined'||userEmail==""){userEmail="anand@analyticsvidhya.com";};let analyticsProdURL="https://brahma.analyticsvidhya.com/api";let analyticsDevURL="https://brahma.aifest.org/api";let analyticsLocalURL="http://localhost:8000/api";let analyticsBaseURL=selectAptAnalyticsURL();let pageLoadTimestamp=Date.now();function getElementsToBeTracked(){let urlPath='/get_element_ids/';let url=analyticsBaseURL+urlPath;let selectorString='';if(selectorString!==''){$(selectorString).on('click',recordClickEvent);}else{$(document).bind('click',recordClickEvent);}}
function recordClickEvent(event){let clickedElementDetails=getElementDetails(event);let urlPath='/events';let url=analyticsBaseURL+urlPath;let currentTimestamp=Date.now();let data={clickedElementDetails:clickedElementDetails,userEmail:userEmail,clientSystemTimestamp:new Date(currentTimestamp).toISOString(),currentPageURI:window.location.href,timeElapsed:String((currentTimestamp-pageLoadTimestamp)/1000),eventType:'click'};let dataJSON=JSON.stringify(data);$.ajax({url:url,xhrFields:{withCredentials:true},data:dataJSON,type:"POST",timeout:3000,async:true,contentType:'application/json',success:function(result){}});}
function recordPageloadEvent(){let urlPath='/events';let url=analyticsBaseURL+urlPath;let data={clientSystemTimestamp:pageLoadTimestamp,userEmail:userEmail,currentPageURI:window.location.href,eventType:'pageload'};let dataJSON=JSON.stringify(data);$.ajax({url:url,xhrFields:{withCredentials:true},data:dataJSON,type:"POST",timeout:3000,async:true,contentType:'application/json',success:function(result){}});}
getElementsToBeTracked();recordPageloadEvent();;